import { useEffect, useMemo, useRef, useState } from "react";
import Modal from "../ui/Modal";
import { Icon } from "../ui/Icon";
import Spinner from "../ui/Spinner";
import { resolveExportScope, countIncluded, countHiddenIncluded, UnknownNodeIdError, NoSelectionError } from "../../utils/mindmapExportScope";
import { exportMindmapImage, estimateExportDimensions, captureMapImageBase64 } from "../../utils/mindmapImageExport";
import { sanitizeExportFilename } from "../../utils/mindmapExportFilename";
import { PRESETS, DEFAULT_APPEARANCE } from "../../utils/mindmapExportAppearance";
import { getExportFormatCapabilities, isDocumentFormat } from "../../utils/mindmapExportFormatCapabilities";
import { createMindmapExport, pollMindmapExportUntilDone, cancelMindmapExport, triggerMindmapExportDownload } from "../../utils/mindmapDocumentExport";
// PR C2: Segmented/Control/Accordion moved to AppearanceControls.jsx so the
// toolbar "Giao diện" editor and this dialog's appearance override step
// share the exact same primitives — never two hand-rolled copies.
import { Segmented, Control, Accordion } from "./AppearanceControls";
import "./exportStudio.css";

const STEPS = [["Nội dung", "Chọn phạm vi xuất", "BookOpen"], ["Định dạng", "Chọn loại file", "FileStack"], ["Giao diện", "Tùy chỉnh hiển thị", "Sliders"], ["Kiểm tra", "Xem trước và xuất", "CheckCircle2"]];
const SCOPES = [["full", "Toàn bộ sơ đồ", "Bao gồm toàn bộ cây, kể cả nhánh đang thu gọn.", "Network"], ["current_branch", "Nhánh hiện tại", "Xuất từ node đang chọn trên canvas.", "GitBranch"], ["selected_branches", "Các nhánh được chọn", "Kết hợp nhiều nhánh trong một lần xuất.", "MousePointerClick"], ["visible", "Phần đang hiển thị", "Chỉ các node đang hiện trên canvas.", "EyeOff"]];
// PR C1: public create formats are exactly these 5. DOCX/XLSX are gone from
// this picker — a job for either still reads/downloads fine if it already
// exists (created before this change, or finished by the worker directly),
// but a NEW one can no longer be started from here; the BE route enforces
// the same restriction independently (app/main.py's _EXPORT_FORMATS).
const IMAGE_FORMATS = [["png", "PNG", "Ảnh sắc nét, hỗ trợ nền trong suốt.", "Image"], ["jpeg", "JPEG", "Ảnh nhẹ, phù hợp để chia sẻ.", "Image"], ["svg", "SVG", "Ảnh vector, phóng to không vỡ nét.", "Spline"], ["webp", "WebP", "Ảnh nhẹ, hỗ trợ nền trong suốt.", "Image"]];
const DOCUMENT_FORMATS = [["pdf", "PDF", "Sơ đồ và dàn ý để học hoặc in.", "FileText"]];
const BACKGROUNDS = [["canvas", "Giống canvas"], ["white", "Trắng"], ["dark", "Tối"], ["transparent", "Trong suốt"], ["custom", "Tùy chỉnh"]];
const DOC_BACKGROUNDS = [["white", "Trắng"], ["dark", "Tối"], ["custom", "Tùy chỉnh"]];
const PRESET_OPTIONS = [["canvas", "Giống canvas"], ["study", "Tài liệu học tập"], ["minimal", "Tối giản"], ["presentation", "Trình bày"]];
const FONT_OPTIONS = [["canvas", "Giống canvas"], ["sans", "Sans (Inter)"], ["serif", "Serif (Spectral)"]];
const DOC_FONT_OPTIONS = [["sans", "Sans (Inter)"], ["serif", "Serif (Spectral)"]];
const COLOR_OPTIONS = [["keep", "Giữ nguyên"], ["monochrome", "Đơn sắc"], ["customPalette", "Bảng màu riêng"]];
const SPACING_OPTIONS = [["compact", "Gọn"], ["normal", "Vừa"], ["spacious", "Rộng"]];
const THICKNESS_OPTIONS = [["thin", "Mảnh"], ["normal", "Vừa"], ["thick", "Đậm"]];
const MARGIN_OPTIONS = [["narrow", "Hẹp"], ["normal", "Vừa"], ["wide", "Rộng"]];
const PAGE_OPTIONS = [["A4", "A4"], ["A3", "A3"]];
const ORIENTATION_OPTIONS = [["portrait", "Dọc"], ["landscape", "Ngang"]];
const PDF_MODE_OPTIONS = [["outline", "Chỉ dàn ý"], ["map", "Chỉ sơ đồ"], ["map_and_outline", "Sơ đồ + dàn ý"]];
const CONTENT_LABELS = { notes: "Ghi chú", citations: "Trích dẫn", sourceNames: "Tên nguồn", relations: "Đường quan hệ", legend: "Chú giải màu nhánh", branding: "Nhãn StudyMap" };

const documentDefaults = () => ({ pdf: getExportFormatCapabilities("pdf").defaults, docx: getExportFormatCapabilities("docx").defaults, xlsx: getExportFormatCapabilities("xlsx").defaults });
const colorKey = (format) => format === "docx" ? "headingColorMode" : format === "xlsx" ? "headerStyleMode" : "branchColorMode";
function backgroundColor(key, custom) { if (key === "canvas") return getComputedStyle(document.documentElement).getPropertyValue("--bg-base").trim() || "#fff"; if (key === "custom") return custom; return { white: "#fff", dark: "#15171C", transparent: "transparent" }[key] || "#fff"; }

export default function ExportStudioDialog({ open, onClose, mind, record, mapId, title, selectedNodeId, selectedBranchIds, onRequestBranchSelection }) {
  const [step, setStep] = useState(0), [furthest, setFurthest] = useState(0);
  const [scopeType, setScopeType] = useState(selectedNodeId ? "current_branch" : "full"), [visibleOnly, setVisibleOnly] = useState(false), [advanced, setAdvanced] = useState(false);
  const [format, setFormat] = useState("png"), [background, setBackground] = useState("canvas"), [customColor, setCustomColor] = useState("#FFFFFF"), [scale, setScale] = useState(2);
  const [filenameOverride, setFilenameOverride] = useState(""), [appearance, setAppearance] = useState(DEFAULT_APPEARANCE), [appearancePreset, setAppearancePreset] = useState("canvas"), [quickPreset, setQuickPreset] = useState(null);
  const [docs, setDocs] = useState(documentDefaults), [includeMapImage, setIncludeMapImage] = useState(false), [openSection, setOpenSection] = useState("colors");
  const [exporting, setExporting] = useState(false), [error, setError] = useState(null), [done, setDone] = useState(null), [jobStatus, setJobStatus] = useState(null), [jobProgress, setJobProgress] = useState(0), [jobId, setJobId] = useState(null);
  const abortRef = useRef(null), isDoc = isDocumentFormat(format), capabilities = useMemo(() => getExportFormatCapabilities(format), [format]), docOptions = docs[format] || docs.pdf, branchCount = selectedBranchIds?.size || 0;
  const custom = () => setQuickPreset(null);
  const changeFormat = (next, manual = true) => { setFormat(next); setOpenSection(isDocumentFormat(next) ? (next === "xlsx" ? "content" : "layout") : "colors"); if (manual) custom(); };
  const updateDoc = (key, value) => { custom(); setAppearancePreset(null); setDocs((all) => ({ ...all, [format]: { ...all[format], [key]: value } })); };
  const updateDocContent = (key, value) => { custom(); setAppearancePreset(null); setDocs((all) => ({ ...all, [format]: { ...all[format], content: { ...all[format].content, [key]: value } } })); };
  const updateAppearance = (patch) => { custom(); setAppearancePreset(null); setAppearance((old) => ({ ...old, ...patch })); };
  const updateContent = (key, value) => { custom(); setAppearancePreset(null); setAppearance((old) => ({ ...old, content: { ...old.content, [key]: value } })); };
  const applyQuick = (name) => { setQuickPreset(name); if (name === "png") { changeFormat("png", false); setBackground("canvas"); setScale(2); setAppearance(PRESETS.canvas); setAppearancePreset("canvas"); } else if (name === "pdf") { changeFormat("pdf", false); setAppearancePreset("study"); const base = getExportFormatCapabilities("pdf").defaults; setDocs((all) => ({ ...all, pdf: { ...base, mode: "map_and_outline", content: { ...base.content, notes: true } } })); } else { changeFormat("webp", false); setBackground("canvas"); setScale(2); setAppearance(PRESETS.canvas); setAppearancePreset("canvas"); } };
  const applyAppearancePreset = (name) => { custom(); setAppearancePreset(name); if (!isDoc) return setAppearance(PRESETS[name]); const visual = PRESETS[name]; setDocs((all) => { const next = { ...all[format], font: visual.font === "serif" ? "serif" : "sans" }; if (capabilities.controls.branchColor || capabilities.controls.headingColor || capabilities.controls.headerStyle) next[colorKey(format)] = visual.branchColorMode; const content = { ...next.content }; Object.keys(content).forEach((key) => { if (key in visual.content) content[key] = visual.content[key]; }); return { ...all, [format]: { ...next, content } }; }); };

  const scopeResult = useMemo(() => { if (!mind?.nodeData) return null; try { const resolved = resolveExportScope({ nodeData: mind.nodeData, scopeType, selectedNodeId, selectedBranchRootIds: selectedBranchIds ? [...selectedBranchIds] : [], visibleOnly }); return { ok: true, count: countIncluded(resolved.includedIds), hidden: countHiddenIncluded(mind.nodeData, resolved.includedIds) }; } catch (e) { if (e instanceof NoSelectionError) return { ok: false, message: scopeType === "selected_branches" ? "Chọn ít nhất một nhánh để tiếp tục." : "Chọn một node trên canvas để tiếp tục." }; if (e instanceof UnknownNodeIdError) return { ok: false, message: "Lựa chọn không còn hợp lệ trên sơ đồ này." }; return { ok: false, message: e.message }; } }, [mind, scopeType, selectedNodeId, selectedBranchIds, visibleOnly]);
  const scopeLabel = { full: "Toàn bộ sơ đồ", current_branch: "Nhánh hiện tại", selected_branches: "Các nhánh được chọn", visible: "Phần đang hiển thị" }[scopeType], filename = sanitizeExportFilename(filenameOverride || title), extension = format === "jpeg" ? "jpg" : format;
  const estimated = useMemo(() => !mind?.map || !scopeResult?.ok || isDoc ? null : estimateExportDimensions({ mind, scopeType, targetNodeId: selectedNodeId, branchRootIds: selectedBranchIds ? [...selectedBranchIds] : [], scale }), [mind, scopeType, selectedNodeId, selectedBranchIds, scale, scopeResult, isDoc]);
  // One idempotency key per export ATTEMPT (each click of export/retry/re-export), never per configuration: a re-export is a new job.
  const attemptKeyRef = useRef(null);
  const newAttemptKey = () => { attemptKeyRef.current = crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`; return attemptKeyRef.current; };
  const inFlightRef = useRef(false);
  const canAdvance = scopeResult?.ok, canExport = canAdvance && !(isDoc && !mapId), effectiveScope = visibleOnly && scopeType === "full" ? "visible" : scopeType;
  const close = () => { if (!exporting) { abortRef.current?.abort(); onClose?.(); } };
  useEffect(() => () => abortRef.current?.abort(), []);
  useEffect(() => { abortRef.current?.abort(); setExporting(false); setError(null); setDone(null); setJobStatus(null); setJobProgress(0); setJobId(null); }, [mapId]);
  // Clears everything tied to one attempt (artifact, job, error, in-flight guard). Configuration is kept.
  const resetTransient = () => { abortRef.current?.abort(); inFlightRef.current = false; setExporting(false); setError(null); setDone(null); setJobStatus(null); setJobProgress(0); setJobId(null); };
  // Reopening always starts at the configuration step with no leftover artifact or job.
  useEffect(() => { if (open) { resetTransient(); setStep(0); setFurthest(0); } }, [open]);
  const startNewExport = () => { resetTransient(); setStep(0); setFurthest(0); };
  const completed = Boolean(done) || jobStatus === "done";

  const runImage = async () => setDone(await exportMindmapImage({ mind, record, scopeType: effectiveScope, targetNodeId: selectedNodeId, branchRootIds: selectedBranchIds ? [...selectedBranchIds] : [], visibleOnly, format, backgroundColor: backgroundColor(background, customColor), scale, title: filename, appearance }));
  const runDocument = async (attemptKey) => { setJobStatus("queued"); setJobProgress(0); setJobId(null); let mapImageBase64; if ((format === "pdf" && docOptions.mode !== "outline") || (format === "docx" && includeMapImage)) mapImageBase64 = await captureMapImageBase64({ mind, record, scopeType: effectiveScope, targetNodeId: selectedNodeId, branchRootIds: selectedBranchIds ? [...selectedBranchIds] : [], visibleOnly }); const created = await createMindmapExport(mapId, { format, scope: { scope_type: effectiveScope, selected_node_id: selectedNodeId, selected_branch_root_ids: selectedBranchIds ? [...selectedBranchIds] : [], include_descendants: true }, options: docOptions, mapImageBase64, idempotencyKey: attemptKey }); setJobId(created.job_id); const controller = new AbortController(); abortRef.current = controller; const final = await pollMindmapExportUntilDone(created.job_id, { signal: controller.signal, onUpdate: (s) => { setJobStatus(s.status); setJobProgress(s.progress || 0); } }); if (final.status === "done") { setDone({ filename: `${filename}.${format}` }); if (final.download_url) triggerMindmapExportDownload(final.download_url); } else if (final.status === "cancelled") throw new Error("Đã hủy xuất tài liệu."); else throw new Error(final.error || "Xuất tài liệu thất bại."); };
  const runExport = async () => { if (!mind || !canExport || inFlightRef.current) return; inFlightRef.current = true; setExporting(true); setError(null); try { if (isDoc) await runDocument(newAttemptKey()); else await runImage(); } catch (e) { if (e?.name !== "AbortError") setError(e?.message || "Không xuất được sơ đồ."); setJobStatus((s) => ["queued", "running"].includes(s) ? "error" : s); } finally { inFlightRef.current = false; setExporting(false); } };
  const cancel = async () => { abortRef.current?.abort(); if (jobId) try { await cancelMindmapExport(jobId); } catch { /* best effort */ } setJobStatus("cancelled"); setExporting(false); };
  const next = () => { if (step === 0 && !canAdvance) return; setStep((old) => { const value = Math.min(3, old + 1); setFurthest((seen) => Math.max(seen, value)); return value; }); };
  const summary = `${scopeLabel} · ${format.toUpperCase()}${scopeResult?.ok ? ` · ${scopeResult.count} node` : ""}`, cta = format === "pdf" ? "Tạo PDF" : format === "docx" ? "Tạo DOCX" : format === "xlsx" ? "Tạo XLSX" : `Xuất ${format.toUpperCase()}`;

  const contentStep = <div className="export-step"><header className="export-step__header"><h3>Nội dung xuất</h3><p>Chọn nhanh một cấu hình hoặc tự thiết lập phạm vi.</p></header><section><div className="export-section-title"><span>Xuất nhanh</span>{!quickPreset && <small>Tùy chỉnh</small>}</div><div className="export-quick-grid">{[["png", "Ảnh PNG", "Image"], ["pdf", "PDF học tập", "FileText"], ["webp", "Ảnh WebP", "Image"]].map(([key, label, icon]) => <button key={key} type="button" className={quickPreset === key ? "is-selected" : ""} aria-pressed={quickPreset === key} onClick={() => applyQuick(key)}><Icon name={icon} size={17} />{label}</button>)}</div></section><section><div className="export-section-title"><span>Phạm vi xuất</span></div><div className="export-choice-list" role="radiogroup" aria-label="Phạm vi xuất">{SCOPES.map(([key, label, hint, icon]) => <label key={key} className={scopeType === key ? "is-selected" : ""}><Icon name={icon} size={18} /><span className="export-choice-list__copy"><strong>{label}</strong><small id={`scope-${key}-desc`}>{key === "current_branch" && !selectedNodeId ? "Chưa chọn node. Chọn một node trên canvas trước." : hint}</small></span>{key === "selected_branches" && <><span className="export-count">{branchCount} nhánh</span><button type="button" className="export-inline-action" onClick={(e) => { e.preventDefault(); onRequestBranchSelection?.(); }}>Chọn trên canvas<span className="sr-only"> {branchCount ? "Chọn lại trên sơ đồ" : "Chọn nhánh trên sơ đồ"}</span></button></>}<input type="radio" name="mm-export-scope" value={key} checked={scopeType === key} aria-describedby={`scope-${key}-desc`} onChange={() => { custom(); setScopeType(key); }} /></label>)}</div></section><section className="export-advanced"><button type="button" aria-expanded={advanced} onClick={() => setAdvanced((v) => !v)}><Icon name="Sliders" size={16} />Nâng cao<Icon name={advanced ? "ChevronUp" : "ChevronDown"} size={16} /></button>{advanced && <div className="export-advanced__body"><label className="export-check"><input name="mm-export-visible-only" type="checkbox" checked={visibleOnly} onChange={(e) => { custom(); setVisibleOnly(e.target.checked); }} /><span><strong>Chỉ giữ node đang hiển thị trong phạm vi đã chọn</strong><small>Áp dụng thêm bộ lọc hiển thị cho phạm vi hiện tại.</small></span></label></div>}</section>{scopeResult && !scopeResult.ok && <div className="export-message export-message--error" role="alert"><Icon name="AlertCircle" size={16} />{scopeResult.message}</div>}</div>;

  const formatStep = <div className="export-step"><header className="export-step__header"><h3>Chọn định dạng</h3><p>Mỗi định dạng chỉ hiển thị các tùy chọn mà hệ thống hỗ trợ.</p></header>{[["Ảnh", IMAGE_FORMATS], ["Tài liệu", DOCUMENT_FORMATS]].map(([group, formats]) => <section key={group}><div className="export-section-title"><span>{group}</span></div>{group === "Tài liệu" && !mapId && <p className="export-helper">Lưu sơ đồ trước khi xuất định dạng tài liệu.</p>}<div className="export-format-grid" role="radiogroup" aria-label={`Định dạng ${group.toLowerCase()}`}>{formats.map(([key, label, hint, icon]) => <label key={key} className={`${format === key ? "is-selected" : ""} ${group === "Tài liệu" && !mapId ? "is-disabled" : ""}`}><Icon name={icon} size={20} /><span><strong>{label}</strong><small>{hint}</small></span><input type="radio" name="mm-export-format" value={key} checked={format === key} disabled={group === "Tài liệu" && !mapId} onChange={() => changeFormat(key)} /></label>)}</div></section>)}</div>;

  const imageColors = <><Control label="Nền"><Segmented options={BACKGROUNDS} value={background} disabled={(v) => v === "transparent" && format === "jpeg"} onChange={(v) => { custom(); setBackground(v); }} />{background === "custom" && <input type="color" aria-label="Màu nền tùy chỉnh" value={customColor} onChange={(e) => { custom(); setCustomColor(e.target.value); }} />}</Control><Control label="Phông chữ"><Segmented options={FONT_OPTIONS} value={appearance.font} onChange={(v) => updateAppearance({ font: v })} /></Control><Control label="Màu nhánh"><Segmented options={COLOR_OPTIONS} value={appearance.branchColorMode} onChange={(v) => updateAppearance({ branchColorMode: v })} /></Control><Control label="Độ dày đường nối"><Segmented options={THICKNESS_OPTIONS} value={appearance.connectorThickness} onChange={(v) => updateAppearance({ connectorThickness: v })} /></Control></>;
  const imageLayout = <><Control label="Khoảng cách"><Segmented options={SPACING_OPTIONS} value={appearance.spacing} onChange={(v) => updateAppearance({ spacing: v })} /></Control><Control label="Độ phân giải"><Segmented options={[[1, "1×"], [2, "2×"], [4, "4×"]]} value={scale} onChange={(v) => { custom(); setScale(v); }} /></Control></>;
  const docColors = <>{capabilities.controls.font && <Control label="Phông chữ"><Segmented options={DOC_FONT_OPTIONS} value={docOptions.font} onChange={(v) => updateDoc("font", v)} /></Control>}{capabilities.controls.background && <Control label="Nền"><Segmented options={DOC_BACKGROUNDS} value={docOptions.background} onChange={(v) => updateDoc("background", v)} /></Control>}{(capabilities.controls.branchColor || capabilities.controls.headingColor || capabilities.controls.headerStyle) && <Control label={format === "docx" ? "Màu tiêu đề" : format === "xlsx" ? "Màu tiêu đề bảng" : "Màu nhánh"}><Segmented options={COLOR_OPTIONS} value={docOptions[colorKey(format)]} onChange={(v) => updateDoc(colorKey(format), v)} /></Control>}</>;
  const docLayout = <>{capabilities.controls.mode && <Control label="Chế độ"><Segmented options={PDF_MODE_OPTIONS} value={docOptions.mode} onChange={(v) => updateDoc("mode", v)} /></Control>}{capabilities.controls.pageSize && <Control label="Khổ giấy"><Segmented options={PAGE_OPTIONS} value={docOptions.pageSize} onChange={(v) => updateDoc("pageSize", v)} /></Control>}{capabilities.controls.orientation && <Control label="Hướng trang"><Segmented options={ORIENTATION_OPTIONS} value={docOptions.orientation} onChange={(v) => updateDoc("orientation", v)} /></Control>}{capabilities.controls.margins && <Control label="Lề"><Segmented options={MARGIN_OPTIONS} value={docOptions.margins} onChange={(v) => updateDoc("margins", v)} /></Control>}{capabilities.controls.singlePage && <label className="export-check"><input type="checkbox" checked={docOptions.singlePage} onChange={(e) => updateDoc("singlePage", e.target.checked)} /><span><strong>Một trang dài duy nhất</strong></span></label>}</>;
  const contentKeys = isDoc ? capabilities.controls.content : ["relations", "citations", "legend", "branding"];
  const appearanceStep = <div className="export-step" data-testid={isDoc ? "doc-appearance" : "image-appearance"}><header className="export-step__header"><h3>Giao diện</h3><p>Các tùy chỉnh được gom theo nhóm để dễ quét.</p></header><section><div className="export-section-title"><span>Mẫu dựng sẵn</span>{!appearancePreset && <small>Tùy chỉnh</small>}</div><Segmented options={PRESET_OPTIONS} value={appearancePreset} onChange={applyAppearancePreset} /></section><div className="export-preview" aria-label="Xem trước giao diện"><div className="export-preview__canvas"><span className="export-preview__root" /><i /><span /><i /><span /></div><div><strong>{PRESET_OPTIONS.find(([v]) => v === appearancePreset)?.[1] || "Tùy chỉnh"}</strong><small>{format.toUpperCase()} · {isDoc ? docOptions?.font : appearance.font}</small></div></div><div className="export-accordions"><Accordion id="export-colors" title="Màu và kiểu chữ" icon="Sliders" open={openSection === "colors"} onToggle={() => setOpenSection(openSection === "colors" ? null : "colors")}>{isDoc ? docColors : imageColors}</Accordion><Accordion id="export-layout" title="Bố cục" icon="Rows3" open={openSection === "layout"} onToggle={() => setOpenSection(openSection === "layout" ? null : "layout")}>{isDoc ? docLayout : imageLayout}</Accordion><Accordion id="export-content" title="Nội dung kèm theo" icon="FileStack" open={openSection === "content"} onToggle={() => setOpenSection(openSection === "content" ? null : "content")}><div className="export-check-grid">{contentKeys.map((key) => <label className="export-check" key={key}><input type="checkbox" checked={isDoc ? !!docOptions.content?.[key] : appearance.content[key]} onChange={(e) => isDoc ? updateDocContent(key, e.target.checked) : updateContent(key, e.target.checked)} /><span><strong>{CONTENT_LABELS[key]}</strong></span></label>)}{isDoc && capabilities.controls.mapImage && <label className="export-check"><input type="checkbox" checked={includeMapImage} onChange={(e) => { custom(); setIncludeMapImage(e.target.checked); }} /><span><strong>Kèm ảnh sơ đồ</strong></span></label>}</div></Accordion><Accordion id="export-filename" title="Tên file" icon="FileText" open={openSection === "filename"} onToggle={() => setOpenSection(openSection === "filename" ? null : "filename")}><label className="export-filename"><span>Tên file</span><div><input type="text" value={filenameOverride} onChange={(e) => { custom(); setFilenameOverride(e.target.value); }} placeholder={sanitizeExportFilename(title)} /><b>.{extension}</b></div><small>Tên không hợp lệ sẽ được tự động làm sạch.</small></label></Accordion></div></div>;

  const included = (isDoc ? Object.entries(docOptions?.content || {}) : Object.entries(appearance.content)).filter(([, value]) => value).map(([key]) => CONTENT_LABELS[key]);
  const reviewStep = <div className="export-step"><header className="export-step__header"><h3>Kiểm tra trước khi xuất</h3><p>Xác nhận cấu hình. Xem trước không thay đổi canvas hiện tại.</p></header>{done ? <div className="export-success"><Icon name="CheckCircle2" size={22} /><div><strong>Đã xuất: {done.filename}</strong><span>File đã tải xuống trình duyệt.</span></div></div> : <div className="export-review" aria-label="Tóm tắt cấu hình xuất"><div className="export-review__thumb"><div className="export-preview__canvas"><span className="export-preview__root" /><i /><span /><i /><span /></div><small>{format.toUpperCase()}</small></div><dl><div><dt>Phạm vi</dt><dd>{scopeLabel}</dd></div><div><dt>Định dạng</dt><dd>{format.toUpperCase()}</dd></div><div><dt>Số node/nhánh</dt><dd>{scopeResult?.ok ? `${scopeResult.count} node${scopeType === "selected_branches" ? ` · ${branchCount} nhánh` : ""}` : "Chưa hợp lệ"}</dd></div><div><dt>Mẫu giao diện</dt><dd>{PRESET_OPTIONS.find(([v]) => v === appearancePreset)?.[1] || "Tùy chỉnh"}</dd></div><div><dt>Nội dung kèm theo</dt><dd>{included.join(", ") || "Không có"}</dd></div><div><dt>Tên file</dt><dd>{filename}.{extension}</dd></div>{estimated && <div><dt>Kích thước</dt><dd>≈{estimated.width}×{estimated.height}px</dd></div>}</dl></div>}{isDoc && jobStatus && <div className="export-message"><Spinner size={14} />{{ queued: "Đang xếp hàng", running: `Đang xử lý (${jobProgress}%)`, done: "Hoàn tất", error: "Thất bại", cancelled: "Đã hủy" }[jobStatus]}</div>}{error && <div className="export-message export-message--error" role="alert"><Icon name="AlertCircle" size={16} />{error}</div>}</div>;

  return <Modal open={open} title="Xuất sơ đồ" subtitle="Chọn phạm vi, định dạng và cách trình bày" onClose={exporting ? undefined : close} maxWidth={1080} fullBleed className="export-studio-modal"><div className="export-studio"><nav className="export-rail" aria-label="Tiến trình xuất sơ đồ"><ol>{STEPS.map(([label, description, icon], index) => { const state = index === step ? "current" : index < furthest ? "completed" : "pending"; return <li key={label} data-state={state}><button type="button" disabled={index > furthest || exporting} aria-current={index === step ? "step" : undefined} onClick={() => index <= furthest && setStep(index)}><span className="export-rail__marker">{state === "completed" ? <Icon name="Check" size={16} /> : <Icon name={icon} size={17} />}</span><span><strong>{label}</strong><small>{description}</small></span></button></li>; })}</ol></nav><div className="export-workspace"><main className="export-workspace__scroll">{step === 0 ? contentStep : step === 1 ? formatStep : step === 2 ? appearanceStep : reviewStep}</main><footer className="export-footer"><div className="export-footer__summary">{summary}</div><div className="export-footer__actions">{step > 0 && !done && <button type="button" className="btn-secondary" disabled={exporting} onClick={() => setStep((v) => v - 1)}>Quay lại</button>}{exporting && ["queued", "running"].includes(jobStatus) ? <button type="button" className="btn-secondary" onClick={cancel}>Hủy xuất</button> : <button type="button" className="btn-secondary" disabled={exporting} onClick={close}>{done ? "Đóng" : "Hủy"}</button>}{step < 3 && <button type="button" className="btn-primary" disabled={(step === 0 && !canAdvance) || exporting} onClick={next}>Tiếp tục</button>}{step === 3 && completed && <><button type="button" className="btn-secondary" disabled={exporting || !canExport} onClick={runExport}><Icon name="RotateCcw" size={15} />Xuất lại</button><button type="button" className="btn-primary" disabled={exporting} onClick={startNewExport}>Tạo bản xuất mới</button></>}{step === 3 && !completed && <button type="button" className="btn-primary" disabled={exporting || !canExport} onClick={runExport}>{exporting ? <><Spinner size={14} />Đang xuất…</> : jobStatus === "error" ? <><Icon name="RotateCcw" size={15} />Thử lại</> : <><Icon name="Download" size={15} />{cta}</>}</button>}</div></footer></div></div></Modal>;
}
