"""initial studymap schema

Revision ID: 102c36a01548
Revises: 
Create Date: 2026-08-20 15:02:47.638877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '102c36a01548'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# RLS: frontend KHÔNG gọi thẳng Supabase — mọi truy vấn đi qua API Flask bằng
# connection string Postgres (role `postgres`, BYPASSRLS). Bật RLS mà KHÔNG tạo
# policy nào = deny-all cho publishable/anon key. Nếu key lộ ra client, không
# bảng nào đọc được. Thêm policy khi (và chỉ khi) cho FE query trực tiếp.
_RLS_TABLES = (
    "users", "documents", "sections", "document_chunks",
    "knowledge_maps", "knowledge_nodes", "knowledge_edges", "knowledge_node_chunks",
    "quizzes", "quiz_questions", "quiz_question_chunks",
    "quiz_attempts", "quiz_answers", "concept_masteries",
    "review_plans", "review_plan_items", "review_item_chunks",
    "jobs", "ai_validation_logs",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='learner', nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('learner','teacher','admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded','processing','completed','failed','deleted')", name='ck_documents_status'),
    sa.CheckConstraint('file_size IS NULL OR file_size > 0', name='ck_documents_file_size'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_user_id', 'documents', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_type', sa.String(length=100), nullable=True),
    sa.Column('result_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','cancelled','timeout')", name='ck_jobs_status'),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name='ck_jobs_progress'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_result', 'jobs', ['result_type', 'result_id'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_user_id', 'jobs', ['user_id'], unique=False)
    op.create_table('ai_validation_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_ref', sa.String(length=255), nullable=True),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('rejected','warning')", name='ck_ai_validation_logs_severity'),
    sa.CheckConstraint("target_type IN ('quiz_question','review_item')", name='ck_ai_validation_logs_target_type'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_validation_logs_job_id', 'ai_validation_logs', ['job_id'], unique=False)
    op.create_index('ix_ai_validation_logs_rule_code', 'ai_validation_logs', ['rule_code'], unique=False)
    op.create_table('knowledge_maps',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generator_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('processing','completed','failed')", name='ck_knowledge_maps_status'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_maps_document_id', 'knowledge_maps', ['document_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('parent_section_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id <> parent_section_id', name='ck_sections_not_self_parent'),
    sa.CheckConstraint('level >= 1', name='ck_sections_level'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sections_document_id', 'sections', ['document_id'], unique=False)
    op.create_index('ix_sections_parent_section_id', 'sections', ['parent_section_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(text)) > 0', name='ck_document_chunks_text_nonempty'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_doc_index')
    )
    op.create_index('ix_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_id', 'document_chunks', ['embedding_id'], unique=False)
    op.create_index('ix_document_chunks_section_id', 'document_chunks', ['section_id'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('map_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('parent_node_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id <> parent_node_id', name='ck_knowledge_nodes_not_self_parent'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['knowledge_maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_nodes_map_id', 'knowledge_nodes', ['map_id'], unique=False)
    op.create_index('ix_knowledge_nodes_parent_node_id', 'knowledge_nodes', ['parent_node_id'], unique=False)
    op.create_index('ix_knowledge_nodes_section_id', 'knowledge_nodes', ['section_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('map_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_review_item_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_attempt_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('quiz_type', sa.String(length=50), nullable=False),
    sa.Column('scope_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy','medium','hard','mixed')", name='ck_quizzes_difficulty'),
    sa.CheckConstraint("quiz_type <> 'practice' OR source_review_item_id IS NOT NULL", name='ck_quizzes_practice_needs_source'),
    sa.CheckConstraint("quiz_type IN ('diagnostic','practice')", name='ck_quizzes_type'),
    sa.CheckConstraint("status IN ('processing','ready','failed')", name='ck_quizzes_status'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['knowledge_maps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_attempt_id'], ['quiz_attempts.id'], name='fk_quizzes_source_attempt', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['source_review_item_id'], ['review_plan_items.id'], name='fk_quizzes_source_review_item', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quizzes_document_id', 'quizzes', ['document_id'], unique=False)
    op.create_index('ix_quizzes_quiz_type', 'quizzes', ['quiz_type'], unique=False)
    op.create_index('ix_quizzes_source_attempt_id', 'quizzes', ['source_attempt_id'], unique=False)
    op.create_index('ix_quizzes_source_review_item_id', 'quizzes', ['source_review_item_id'], unique=False)
    op.create_index('ix_quizzes_status', 'quizzes', ['status'], unique=False)
    op.create_index('ix_quizzes_user_id', 'quizzes', ['user_id'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('map_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_node_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_node_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relation_type IN ('parent_child','supports','prerequisite','contrasts','related')", name='ck_knowledge_edges_relation_type'),
    sa.CheckConstraint('source_node_id <> target_node_id', name='ck_knowledge_edges_no_self_loop'),
    sa.ForeignKeyConstraint(['map_id'], ['knowledge_maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_edges_map_id', 'knowledge_edges', ['map_id'], unique=False)
    op.create_index('ix_knowledge_edges_source_node_id', 'knowledge_edges', ['source_node_id'], unique=False)
    op.create_index('ix_knowledge_edges_target_node_id', 'knowledge_edges', ['target_node_id'], unique=False)
    op.create_table('knowledge_node_chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('node_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'chunk_id', name='uq_knowledge_node_chunks')
    )
    op.create_index('ix_knowledge_node_chunks_chunk_id', 'knowledge_node_chunks', ['chunk_id'], unique=False)
    op.create_index('ix_knowledge_node_chunks_node_id', 'knowledge_node_chunks', ['node_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quiz_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('incorrect_count', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('in_progress','submitted','graded','cancelled')", name='ck_quiz_attempts_status'),
    sa.CheckConstraint('correct_count IS NULL OR incorrect_count IS NULL OR correct_count + incorrect_count <= total_questions', name='ck_quiz_attempts_counts'),
    sa.CheckConstraint('percentage IS NULL OR (percentage BETWEEN 0 AND 100)', name='ck_quiz_attempts_percentage'),
    sa.CheckConstraint('score IS NULL OR score <= max_score', name='ck_quiz_attempts_score'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_attempts_quiz_id', 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index('ix_quiz_attempts_status', 'quiz_attempts', ['status'], unique=False)
    op.create_index('ix_quiz_attempts_user_id', 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quiz_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('knowledge_node_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('concept_tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy','medium','hard')", name='ck_quiz_questions_difficulty'),
    sa.CheckConstraint("question_type IN ('multiple_choice','true_false','short_answer')", name='ck_quiz_questions_type'),
    sa.CheckConstraint('length(trim(correct_answer)) > 0', name='ck_quiz_questions_answer_nonempty'),
    sa.CheckConstraint('length(trim(explanation)) > 0', name='ck_quiz_questions_explanation_nonempty'),
    sa.CheckConstraint('length(trim(question_text)) > 0', name='ck_quiz_questions_text_nonempty'),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_questions_knowledge_node_id', 'quiz_questions', ['knowledge_node_id'], unique=False)
    op.create_index('ix_quiz_questions_quiz_id', 'quiz_questions', ['quiz_id'], unique=False)
    op.create_index('ix_quiz_questions_quiz_order', 'quiz_questions', ['quiz_id', 'order_index'], unique=False)
    op.create_index('ix_quiz_questions_section_id', 'quiz_questions', ['section_id'], unique=False)
    op.create_table('concept_masteries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('attempt_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('knowledge_node_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('concept_name', sa.String(length=255), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('earned_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('mastered','light_review','review_needed','critical_gap')", name='ck_concept_masteries_status'),
    sa.CheckConstraint('correct_count <= total_count', name='ck_concept_masteries_correct'),
    sa.CheckConstraint('earned_score <= total_count', name='ck_concept_masteries_earned'),
    sa.CheckConstraint('mastery_score BETWEEN 0 AND 1', name='ck_concept_masteries_score'),
    sa.CheckConstraint('total_count > 0', name='ck_concept_masteries_total'),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'concept_name', name='uq_concept_masteries_attempt_concept')
    )
    op.create_index('ix_concept_masteries_attempt_id', 'concept_masteries', ['attempt_id'], unique=False)
    op.create_index('ix_concept_masteries_concept_name', 'concept_masteries', ['concept_name'], unique=False)
    op.create_index('ix_concept_masteries_document_id', 'concept_masteries', ['document_id'], unique=False)
    op.create_index('ix_concept_masteries_status', 'concept_masteries', ['status'], unique=False)
    op.create_index('ix_concept_masteries_user_id', 'concept_masteries', ['user_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('attempt_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('question_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("verdict IS NULL OR verdict IN ('correct','partial','incorrect')", name='ck_quiz_answers_verdict'),
    sa.CheckConstraint('score IS NULL OR score IN (0, 0.5, 1)', name='ck_quiz_answers_score'),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_quiz_answers_attempt_question')
    )
    op.create_index('ix_quiz_answers_attempt_id', 'quiz_answers', ['attempt_id'], unique=False)
    op.create_index('ix_quiz_answers_question_id', 'quiz_answers', ['question_id'], unique=False)
    op.create_table('quiz_question_chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('question_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'chunk_id', name='uq_quiz_question_chunks')
    )
    op.create_index('ix_quiz_question_chunks_chunk_id', 'quiz_question_chunks', ['chunk_id'], unique=False)
    op.create_index('ix_quiz_question_chunks_question_id', 'quiz_question_chunks', ['question_id'], unique=False)
    op.create_table('review_plans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('attempt_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', name='uq_review_plans_attempt')
    )
    op.create_index('ix_review_plans_attempt_id', 'review_plans', ['attempt_id'], unique=False)
    op.create_index('ix_review_plans_user_id', 'review_plans', ['user_id'], unique=False)
    op.create_table('review_plan_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('review_plan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('concept_mastery_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('knowledge_node_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('mastery_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('review_tasks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('light_review','review_needed','critical_gap')", name='ck_review_plan_items_status'),
    sa.CheckConstraint('priority >= 1', name='ck_review_plan_items_priority'),
    sa.ForeignKeyConstraint(['concept_mastery_id'], ['concept_masteries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_plan_id'], ['review_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_plan_id', 'priority', name='uq_review_plan_items_priority')
    )
    op.create_index('ix_review_plan_items_priority', 'review_plan_items', ['priority'], unique=False)
    op.create_index('ix_review_plan_items_review_plan_id', 'review_plan_items', ['review_plan_id'], unique=False)
    op.create_table('review_item_chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('review_item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_plan_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_item_id', 'chunk_id', name='uq_review_item_chunks')
    )
    op.create_index('ix_review_item_chunks_chunk_id', 'review_item_chunks', ['chunk_id'], unique=False)
    op.create_index('ix_review_item_chunks_review_item_id', 'review_item_chunks', ['review_item_id'], unique=False)
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        # CHỈ ENABLE, KHÔNG FORCE: FORCE áp RLS lên cả owner → BE (role postgres,
        # owner) sẽ tự khoá chính mình vì không có policy nào.
        op.execute('ALTER TABLE public."%s" ENABLE ROW LEVEL SECURITY' % table)



def downgrade() -> None:
    for table in _RLS_TABLES:
        op.execute('ALTER TABLE public."%s" DISABLE ROW LEVEL SECURITY' % table)

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_item_chunks_review_item_id', table_name='review_item_chunks')
    op.drop_index('ix_review_item_chunks_chunk_id', table_name='review_item_chunks')
    op.drop_table('review_item_chunks')
    op.drop_index('ix_review_plan_items_review_plan_id', table_name='review_plan_items')
    op.drop_index('ix_review_plan_items_priority', table_name='review_plan_items')
    op.drop_table('review_plan_items')
    op.drop_index('ix_review_plans_user_id', table_name='review_plans')
    op.drop_index('ix_review_plans_attempt_id', table_name='review_plans')
    op.drop_table('review_plans')
    op.drop_index('ix_quiz_question_chunks_question_id', table_name='quiz_question_chunks')
    op.drop_index('ix_quiz_question_chunks_chunk_id', table_name='quiz_question_chunks')
    op.drop_table('quiz_question_chunks')
    op.drop_index('ix_quiz_answers_question_id', table_name='quiz_answers')
    op.drop_index('ix_quiz_answers_attempt_id', table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index('ix_concept_masteries_user_id', table_name='concept_masteries')
    op.drop_index('ix_concept_masteries_status', table_name='concept_masteries')
    op.drop_index('ix_concept_masteries_document_id', table_name='concept_masteries')
    op.drop_index('ix_concept_masteries_concept_name', table_name='concept_masteries')
    op.drop_index('ix_concept_masteries_attempt_id', table_name='concept_masteries')
    op.drop_table('concept_masteries')
    op.drop_index('ix_quiz_questions_section_id', table_name='quiz_questions')
    op.drop_index('ix_quiz_questions_quiz_order', table_name='quiz_questions')
    op.drop_index('ix_quiz_questions_quiz_id', table_name='quiz_questions')
    op.drop_index('ix_quiz_questions_knowledge_node_id', table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index('ix_quiz_attempts_user_id', table_name='quiz_attempts')
    op.drop_index('ix_quiz_attempts_status', table_name='quiz_attempts')
    op.drop_index('ix_quiz_attempts_quiz_id', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index('ix_knowledge_node_chunks_node_id', table_name='knowledge_node_chunks')
    op.drop_index('ix_knowledge_node_chunks_chunk_id', table_name='knowledge_node_chunks')
    op.drop_table('knowledge_node_chunks')
    op.drop_index('ix_knowledge_edges_target_node_id', table_name='knowledge_edges')
    op.drop_index('ix_knowledge_edges_source_node_id', table_name='knowledge_edges')
    op.drop_index('ix_knowledge_edges_map_id', table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index('ix_quizzes_user_id', table_name='quizzes')
    op.drop_index('ix_quizzes_status', table_name='quizzes')
    op.drop_index('ix_quizzes_source_review_item_id', table_name='quizzes')
    op.drop_index('ix_quizzes_source_attempt_id', table_name='quizzes')
    op.drop_index('ix_quizzes_quiz_type', table_name='quizzes')
    op.drop_index('ix_quizzes_document_id', table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index('ix_knowledge_nodes_section_id', table_name='knowledge_nodes')
    op.drop_index('ix_knowledge_nodes_parent_node_id', table_name='knowledge_nodes')
    op.drop_index('ix_knowledge_nodes_map_id', table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index('ix_document_chunks_section_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedding_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_sections_parent_section_id', table_name='sections')
    op.drop_index('ix_sections_document_id', table_name='sections')
    op.drop_table('sections')
    op.drop_index('ix_knowledge_maps_document_id', table_name='knowledge_maps')
    op.drop_table('knowledge_maps')
    op.drop_index('ix_ai_validation_logs_rule_code', table_name='ai_validation_logs')
    op.drop_index('ix_ai_validation_logs_job_id', table_name='ai_validation_logs')
    op.drop_table('ai_validation_logs')
    op.drop_index('ix_jobs_user_id', table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_result', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_documents_user_id', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
