"""documents.metadata_json for ingest runtime state

Revision ID: ea56c24b17bb
Revises: 102c36a01548
Create Date: 2026-08-20 15:33:30.867703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea56c24b17bb'
down_revision: Union[str, Sequence[str], None] = '102c36a01548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key('fk_quizzes_source_review_item', 'quizzes', 'review_plan_items', ['source_review_item_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_quizzes_source_attempt', 'quizzes', 'quiz_attempts', ['source_attempt_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_quizzes_source_attempt', 'quizzes', type_='foreignkey')
    op.drop_constraint('fk_quizzes_source_review_item', 'quizzes', type_='foreignkey')
    op.drop_column('documents', 'metadata_json')
    # ### end Alembic commands ###
