"""Section 8/9 (final hardening round): generates and RETAINS the exact
named QA specimens the round asked for, against a deterministic 60+-node
fixture, and validates each by reopening it with the same library that
wrote it — never by "a file was created".

  full-map.pdf            (BE/qa-artifacts/)
  selected-branches.docx  (BE/qa-artifacts/)
  selected-branches.xlsx  (BE/qa-artifacts/)

PNG/full-map.png, JPEG/selected-branch.jpeg and SVG/multi-branch.svg are
the client-side formats — their exact-named specimens are generated by the
real-Chromium Playwright suite (FE/e2e-fixture/export-studio.spec.js's
"Section 8 artifact quality gate" test), not here; this backend has no
rendering surface for them.
"""
from __future__ import annotations

import io
from pathlib import Path

import docx
import fitz
from openpyxl import load_workbook

from services.mindmap.export.scope import resolve_export_scope
from services.mindmap.export.tree import build_export_tree
from services.mindmap.export.docx_serializer import serialize_docx
from services.mindmap.export.xlsx_serializer import serialize_xlsx
from services.mindmap.export.pdf_serializer import serialize_pdf

QA_DIR = Path(__file__).parent.parent / "qa-artifacts"
QA_DIR.mkdir(exist_ok=True)


def _deterministic_60_node_fixture():
    """Same shape as FE's mindmapFixtures.js (4 main branches x 3 sub x 3
    leaf = 52, + root = 53, + 7 extras = 60) — independently built here so
    this test has no dependency on the FE fixture module."""
    nodes = [{"id": "root", "parent": None, "kind": "root", "title": "Bản đồ tư duy: Hệ thống StudyMap", "order": 0}]
    mains = ["Kiến trúc hệ thống", "Bảo mật & xác thực", "Hiệu năng & mở rộng", "Trải nghiệm người dùng"]
    subs = ["Nguyên lý", "Triển khai thực tế", "Rủi ro & hạn chế"]
    leaves = ["Định nghĩa", "Ví dụ cụ thể", "Ghi chú vận hành"]
    relation_candidates = []
    for mi, main in enumerate(mains):
        main_id = f"m{mi}"
        nodes.append({"id": main_id, "parent": "root", "kind": "section", "title": main, "order": mi})
        for si, sub in enumerate(subs):
            sub_id = f"{main_id}-s{si}"
            nodes.append({"id": sub_id, "parent": main_id, "kind": "section", "title": f"{sub} — {main}", "order": si})
            for li, leaf in enumerate(leaves):
                leaf_id = f"{sub_id}-l{li}"
                has_citation = (mi + si + li) % 3 == 0
                nodes.append({
                    "id": leaf_id, "parent": sub_id, "kind": "idea", "title": f"{leaf}: {sub.lower()}", "order": li,
                    "note": f"Ghi chú cho {leaf.lower()}" if li == 1 else "",
                    "chunk_refs": [f"c{mi}{si}{li}"] if has_citation else [],
                })
                relation_candidates.append(leaf_id)
    extras = [("m0-s0", "Ràng buộc lịch sử"), ("m1-s0", "Chính sách xoay khoá"),
              ("m2-s1", "Ngưỡng cảnh báo"), ("m3-s0", "Phản hồi người dùng"),
              ("m0-s1", "Kịch bản song song"), ("m1-s2", "Log truy vết"), ("m3-s2", "Kiểm thử khả năng tiếp cận")]
    for i, (parent, title) in enumerate(extras):
        nodes.append({"id": f"extra{i}", "parent": parent, "kind": "idea", "title": title, "order": 99 + i})
    relations = [
        {"source": relation_candidates[1], "target": relation_candidates[10], "type": "relates_to", "label": ""},
        {"source": relation_candidates[4], "target": relation_candidates[22], "type": "leads_to", "label": ""},
    ]
    return nodes, relations


def test_full_map_pdf_artifact_retained_and_valid():
    nodes, relations = _deterministic_60_node_fixture()
    scope = resolve_export_scope(nodes, scope_type="full")
    assert len(scope["included_ids"]) >= 60
    tree = build_export_tree(nodes, relations, scope["root_ids"], scope["included_ids"], title="Bản đồ tư duy: Hệ thống StudyMap")

    file_bytes = serialize_pdf(tree, mode="outline", content={"notes": True, "relations": True})
    (QA_DIR / "full-map.pdf").write_bytes(file_bytes)

    doc = fitz.open(stream=file_bytes, filetype="pdf")
    assert doc.page_count >= 1
    for page in doc:
        assert page.get_text().strip() or page.get_images()  # no blank pages
    full_text = "".join(page.get_text() for page in doc)
    assert "Kiến trúc hệ thống" in full_text
    doc.close()


def test_selected_branches_docx_artifact_retained_and_valid():
    nodes, relations = _deterministic_60_node_fixture()
    scope = resolve_export_scope(nodes, scope_type="selected_branches", selected_branch_root_ids=["m0", "m1"])
    tree = build_export_tree(nodes, relations, scope["root_ids"], scope["included_ids"], title="Bản đồ tư duy: Hệ thống StudyMap")

    file_bytes = serialize_docx(tree, content={"notes": True, "citations": True, "relations": True})
    (QA_DIR / "selected-branches.docx").write_bytes(file_bytes)

    doc = docx.Document(io.BytesIO(file_bytes))
    headings = [p.text for p in doc.paragraphs if p.style.name.startswith("Heading")]
    assert "Kiến trúc hệ thống" in headings
    assert "Bảo mật & xác thực" in headings
    assert not any("Hiệu năng" in h for h in headings)  # excluded scope holds


def test_selected_branches_xlsx_artifact_retained_and_valid():
    nodes, relations = _deterministic_60_node_fixture()
    scope = resolve_export_scope(nodes, scope_type="selected_branches", selected_branch_root_ids=["m0", "m1"])
    tree = build_export_tree(nodes, relations, scope["root_ids"], scope["included_ids"], title="Bản đồ tư duy: Hệ thống StudyMap")

    file_bytes = serialize_xlsx(tree, content={"notes": True, "sourceNames": True, "citations": True, "relations": True})
    (QA_DIR / "selected-branches.xlsx").write_bytes(file_bytes)

    wb = load_workbook(io.BytesIO(file_bytes))
    assert "Summary" in wb.sheetnames
    assert "Nodes" in wb.sheetnames
    topics = [row[0] for row in wb["Nodes"].iter_rows(min_row=2, min_col=6, max_col=6, values_only=True)]
    assert "Kiến trúc hệ thống" in topics
    assert not any(t and "Hiệu năng" in t for t in topics)
    # parent/depth/order sanity — every row's parent is present EXCEPT the
    # scope's own selected-branch roots (m0, m1), whose real parent ("root")
    # is legitimately outside a branch-only scope by design.
    ids = {row[0] for row in wb["Nodes"].iter_rows(min_row=2, min_col=1, max_col=1, values_only=True)}
    for row in wb["Nodes"].iter_rows(min_row=2, values_only=True):
        node_id, parent_id = row[0], row[1]
        if parent_id and node_id not in ("m0", "m1"):
            assert parent_id in ids, node_id
